//! Generated by guest/builder -- do not edit. Regenerate with
//! `cargo run --manifest-path guest/builder/Cargo.toml --release`.

/// Image id of the committed guest ELF, as the words risc0 verifies against.
pub const WICKRA_ZK_GUEST_ID: [u32; 8] = [
    0x517f_d55f,
    0x0dfb_40d6,
    0xae44_efa2,
    0x089c_6e50,
    0xe7ac_607d,
    0xfd4c_646c,
    0xbb76_47ef,
    0x2251_3e62,
];

/// The same image id as lower-case hex -- what a verifier pins and a
/// release names. `wickra_zk_host::guest_id()` returns exactly this.
pub const WICKRA_ZK_GUEST_ID_HEX: &str =
    "5fd57f51d640fb0da2ef44ae506e9c087d60ace76c644cfdef4776bb623e5122";
