//! The compiled wickra-zk guest program, committed.
//!
//! This crate exposes the guest to the host:
//!
//! - [`WICKRA_ZK_GUEST_ELF`] — the guest program the prover executes, the
//!   bytes of `elf/wickra-zk-guest.bin`.
//! - [`WICKRA_ZK_GUEST_ID`] — the image ID the verifier checks a receipt
//!   against; it is the cryptographic commitment to *which* program ran.
//!   [`WICKRA_ZK_GUEST_ID_HEX`] is the same id as the hex string a verifier
//!   pins.
//!
//! Both are generated by `guest/builder`, the one crate in this repository
//! that needs the risc0 toolchain: it compiles `guest/` (the detached RISC-V
//! crate) through risc0-build and writes the ELF and the id here. They are
//! committed, so this crate -- and every crate and binding above it -- builds
//! with plain Rust, on docs.rs and inside a wheel container alike. CI rebuilds
//! the guest with `RISC0_USE_DOCKER=1`, the reproducible build risc0 designs
//! the image id for, and fails on a diff, so the committed bytes are always
//! the ones the committed source produces.
//!
//! The host crate (`wickra-zk-host`) proves with the ELF and verifies against
//! the ID, so a receipt is only accepted for this exact guest.

mod guest_id;

pub use guest_id::{WICKRA_ZK_GUEST_ID, WICKRA_ZK_GUEST_ID_HEX};

/// The guest program the prover runs.
pub const WICKRA_ZK_GUEST_ELF: &[u8] = include_bytes!("../elf/wickra-zk-guest.bin");
