//! Export the built guest into `guest/methods`, where it is committed.
//!
//! `build.rs` compiled the guest through risc0-build and generated
//! `$OUT_DIR/methods.rs` with the ELF bytes and the image id. This binary
//! writes them where the host reads them:
//!
//! - `guest/methods/elf/wickra-zk-guest.bin` -- the program the prover runs;
//! - `guest/methods/src/guest_id.rs` -- the image id the verifier pins.
//!
//! The published crates carry the committed artefact, so a consumer -- or
//! docs.rs, or a wheel built inside a manylinux container -- needs no risc0
//! toolchain. The guest-build job rebuilds it with `RISC0_USE_DOCKER=1`, the
//! reproducible build risc0 designs the image id for, and fails on a diff, so
//! the committed bytes are always the ones the committed source produces.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

// risc0-build writes the image id as bare decimal words, and a guest path
// constant this binary has no use for.
#[allow(clippy::unreadable_literal, dead_code)]
mod generated {
    include!(concat!(env!("OUT_DIR"), "/methods.rs"));
}
use generated::{WICKRA_ZK_GUEST_ELF, WICKRA_ZK_GUEST_ID};

fn main() {
    let methods = Path::new(env!("CARGO_MANIFEST_DIR")).join("../methods");
    let elf = methods.join("elf/wickra-zk-guest.bin");
    let id = methods.join("src/guest_id.rs");

    fs::create_dir_all(elf.parent().expect("elf path has a parent"))
        .expect("create guest/methods/elf");
    fs::write(&elf, WICKRA_ZK_GUEST_ELF).expect("write the guest ELF");

    // Laid out the way rustfmt lays it out, so the committed file passes
    // `cargo fmt --check` as generated.
    let mut words = String::new();
    let mut hex = String::new();
    for word in WICKRA_ZK_GUEST_ID {
        writeln!(words, "    0x{:04x}_{:04x},", word >> 16, word & 0xffff)
            .expect("write to a String");
        for byte in word.to_le_bytes() {
            write!(hex, "{byte:02x}").expect("write to a String");
        }
    }
    let source = format!(
        "//! Generated by guest/builder -- do not edit. Regenerate with\n\
         //! `cargo run --manifest-path guest/builder/Cargo.toml --release`.\n\
         \n\
         /// Image id of the committed guest ELF, as the words risc0 verifies against.\n\
         pub const WICKRA_ZK_GUEST_ID: [u32; 8] = [\n\
         {words}\
         ];\n\
         \n\
         /// The same image id as lower-case hex -- what a verifier pins and a\n\
         /// release names. `wickra_zk_host::guest_id()` returns exactly this.\n\
         pub const WICKRA_ZK_GUEST_ID_HEX: &str =\n\
         \x20   \"{hex}\";\n"
    );
    fs::write(&id, source).expect("write guest_id.rs");

    println!(
        "wrote {} ({} bytes) and {} (image id {hex})",
        elf.display(),
        WICKRA_ZK_GUEST_ELF.len(),
        id.display()
    );
}
