/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * A prover driven by JSON commands.
 *
 * Holds no state -- the host's command surface is a free function -- but is
 * handle-shaped so every binding in the family reads the same way.
 */
export declare class Prover {
  /** Create a prover. */
  constructor()
  /** Apply a command JSON and return the resulting response JSON. */
  command(cmdJson: string): string
  /** The library version. */
  version(): string
}

/** The library version. */
export declare function version(): string
