/* auto-generated by NAPI-RS */
/* eslint-disable */
/** A stateless prover driven by JSON commands. */
export declare class Prover {
  /** Create a stateless prover. */
  constructor()
  /** Apply a command JSON and return the resulting response JSON. */
  command(cmdJson: string): string
  /** The library version. */
  version(): string
}

/** The library version. */
export declare function version(): string
