/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

/**
 * A prover driven by JSON commands.
 *
 * The host's command surface is a free function; the handle exists so every
 * binding in the family reads the same way. It carries the host version it
 * was created against, which is what `version()` reports.
 */
export declare class Prover {
  /** Create a prover. */
  constructor()
  /** Apply a command JSON and return the resulting response JSON. */
  command(cmdJson: string): string
  /** The library version. */
  version(): string
}

/** The library version. */
export declare function version(): string
